# build-and-deploy-development.yml
name: Build and Deploy Development

on:
  push:
    branches: 
    - 'master'
  workflow_dispatch:
    inputs:
      commit:
        description: 'commit / branch [5eb6c5e/master]'
        required: false

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ '14.18.3' ]
    name: node ${{ matrix.node-version }}
    steps:
      - name: condition for commit if empty
        if: "github.event.inputs.commit == ''"
        run: |
          echo "commit=master" >> $GITHUB_ENV

      - name: condition for commit if set
        if: "github.event.inputs.commit != ''"
        run: |
          echo "commit=${{ github.event.inputs.commit }}" >> $GITHUB_ENV

      - name: checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ env.commit }}
          fetch-depth: 0

      - name: use node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: npm ci && build
        run: |
          npm ci
          npm run build

      - name: deploy
        uses: crazy-max/ghaction-github-pages@v1
        with:
          target_branch: gh-pages
          build_dir: build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_REPO_TOKEN }}