# build-and-deploy-development.yml
name: Build and Deploy Development

on:
  push:
    branches: 
    - 'master'
  workflow_dispatch:
    inputs:
      commit:
        description: 'commit / branch [5eb6c5e/master]'
        required: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@master

    - name: setup node
      uses: actions/setup-node@v1
      with:
        node-version: '14.18.3'
